In [2]:
import pandas as pd
import numpy as np

# Creating a dataframe from an array

## Option 1

In [4]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [12]:
# creating a dataframe
df = pd.DataFrame(data,
             index = ["row1","row2", "row3"],
             columns=["col1", "col2"])

In [14]:
# showing the data frame
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

## Option 2

In [15]:
# creating an array with list shape
data2 = [[1,4], [2,5], [3,6]]

In [16]:
# creating a dataframe
df2 = pd.DataFrame(data2,
                  index = ["row1","row2", "row3"],
                  columns=["col1", "col2"])

In [17]:
# showing the dataframe
df2

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Creating a DataFrame from a dictionary

In [19]:
# list used for this example
states = ["Texas", "Georgia", "Michigan","Florida"]

population = [12345678, 59874635, 8749587, 94536125]

In [20]:
# sorting lists within a dictionary
dict_states = {'States':states, 'Population':population}

In [21]:
# Creating the dataframe
df_states = pd.DataFrame(dict_states)

In [22]:
# Showing the dataframe
df_states

     States  Population
0     Texas    12345678
1   Georgia    59874635
2  Michigan     8749587
3   Florida    94536125

# Creating a DataFrame from a csv file

In [ ]:
# Reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [25]:
# showing the dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75